"""added reminders  reminders

Revision ID: 313940398757
Revises: 9ddd711f85b8
Create Date: 2024-10-01 18:17:43.194335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '313940398757'
down_revision = '9ddd711f85b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminder', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminder', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
